spring:
  profiles:
    active: docker
  application:
    name: echo-service
  zipkin:
    baseUrl: http://zipkin:9411
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    instance:
      preferIpAddress: true